site_name: IntroDB-Spring-2021
site_url: https://fduxuan.github.io/IntroDB-Spring-2021/
repo_url: https://github.com/fduxuan/IntroDB-Spring-2021
repo_name: fduxuan/IntroDB-Spring-2021
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
  palette:
    primary: black
    accent: light blue

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences


extra_css:
  - stylesheets/extra.css


nav:
  - HomePage: index.md
  - Assignment:
      - Assignment-1: Assignment/assignment1.md
      - Assignment-2: Assignment/assignment2.md
      - Assignment-3: Assignment/assignment3.md
  - Project:
      - Project-1: Project/project-1.md
      - Project-2: Project/project-2.md
  - Answer:
      - Assignment-2 Answer: Answer/assignment-2.md
